# Site settings
author: Ola Bakar
title: Why Studying Software Engineering
header-img: img/home-bg.png
email: eniolar10@gmail.com
copyright_name: Ola Bakar
description: > # this means to ignore newlines until "baseurl:"
  Global Value
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  eniolar10

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
